# Generated by Django 3.2.4 on 2021-06-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0003_contact_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='neighborhood_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='neighbourhood_name',
            new_name='name',
        ),
    ]
